name: Generate Snake Animation
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Lirzh
          gif_out_path: ./output/github-contribution-grid-snake.svg
          svg_out_path: ./output/github-contribution-grid-snake.svg
          svg_dark_out_path: ./output/github-contribution-grid-snake-dark.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}